
SS_INSTALL_DIR=/usr/local/solverselecter
include $(SS_INSTALL_DIR)/Makefile.inc 

all: ex01 ex02 ex03 ex04 

ex01:  
	$(SS) -g $(SS_INCLUDE) -o ex01.ss ex01.cpp $(SS_LIBS)   
	
ex02: 
	$(SS) -g $(SS_INCLUDE) -o ex02.ss ex02.cpp $(SS_LIBS)   

ex03: 
	$(SS) -g $(SS_INCLUDE) -o ex03.ss ex03.cpp $(SS_LIBS)   

ex04: 
	$(SS) -g $(SS_INCLUDE) -o ex04.ss ex04.cpp $(SS_LIBS)   

ex05: 
	$(SS) -g $(SS_INCLUDE) -o ex05.ss ex05.cpp $(SS_LIBS)   
clean: 
	rm -f *.ss 

