###############################################################################
################### MOOSE Application Standard Makefile #######################
###############################################################################
#
# Optional Environment variables
# MOOSE_DIR        - Root directory of the MOOSE project
# MODULE_DIR       - Location of the MOOSE modules directory
# FRAMEWORK_DIR    - Location of the MOOSE framework
#
###############################################################################
MODULE_DIR         ?= $(shell dirname `pwd`)
MOOSE_DIR          ?= $(shell dirname $(MODULE_DIR))
FRAMEWORK_DIR      ?= $(MOOSE_DIR)/framework
ADDITIONAL_CPPFLAGS += -Wall -Wextra
###############################################################################


### Add these three lines to the Makefile in the application main 
### directory ( e.g. moose/modules/<module>/Makefile ) to add ss-lite
### support for that module, tutorial or application. Note, you only
### need to do this in the top level application: There is no need to 
## do this in every module that an application uses. 

######################################################
include /usr/local/solverselecter-lite/Makefile.inc 
ADDITIONAL_INCLUDES += $(SS_INCLUDE)
ADDITIONAL_LIBS += $(SS_LIBS) 
#####################################################


# framework
include $(FRAMEWORK_DIR)/build.mk
include $(FRAMEWORK_DIR)/moose.mk

#dependency on tensor_mechanics
TENSOR_MECHANICS   := yes
SKIP_LOADER        := yes
include $(MODULE_DIR)/modules.mk

# dep apps
APPLICATION_DIR    := $(MODULE_DIR)/solid_mechanics
APPLICATION_NAME   := solid_mechanics
BUILD_EXEC         := yes
GEN_REVISION       := no
include            $(FRAMEWORK_DIR)/app.mk

###############################################################################
# Additional special case targets should be added here
