 
  // The names files suggests the fset is AbsoluteTrace, OneNorm, ColDiagDom, SymmetricInf, DiagonalMean, Frob, nnz 

  #define ABSOLUTETRACE _ABSOLUTETRACE 
  #define ONENORM _ONENORM 
  #define COLDIAGONALDOMINANCE _COLDIAGONALDOMINANCE 
  #define SYMMETRICINFINITYNORM _SYMMETRICINFINITYNORM 
  #define DIAGONALMEAN _DIAGONALMEAN 
  #define FROBENIUSNORM _FROBENIUSNORM 
  #define NNZ _NNZ 
 
   // All the rest should be set to zero!!! This is important -- Do not simply remove 
   // ( %s/ _/ 0 \/\/ / gc ) 
   //
  #define AVGNONZEROSPERROW 0//AVGNONZEROSPERROW 
  #define ABSOLUTENONZEROSUM 0//ABSOLUTENONZEROSUM 
  #define AVERAGEDIAGONALDISTANCE 0//AVERAGEDIAGONALDISTANCE            
  #define ROWVARIANCE 0//ROWVARIANCE 
  #define TRACE 0//TRACE 
  #define DIAGONALAVERAGE 0//DIAGONALAVERAGE    
  #define DIAGONALNONZEROS 0//DIAGONALNONZEROS   
  #define INFINITYNORM 0//INFINITYNORM 
  #define MAXNONZEROSPERROW 0//MAXNONZEROSPERROW 
  #define DIAGONALSIGN 0//DIAGONALSIGN 
  #define LOWERBANDWIDTH 0//LOWERBANDWIDTH 
  #define UPPERBANDWIDTH 0//UPPERBANDWIDTH 
  #define ROWDIAGONALDOMINANCE 0//ROWDIAGONALDOMINANCE 
  #define MINNONZEROSPERROW 0//MINNONZEROSPERROW 
  #define COLUMNVARIANCE 0//COLUMNVARIANCE 
  #define SYMMETRICITY 0//SYMMETRICITY 
  #define NONZEROPATTERNSYMMETRY 0//NONZEROPATTERNSYMMETRY 
  #define SYMMETRICFROBENIUSNORM 0//SYMMETRICFROBENIUSNORM 
  #define ANTISYMMETRICINFINITYNORM 0//ANTISYMMETRICINFINITYNORM 
  #define ANTISYMMETRICFROBENIUSNORM 0//ANTISYMMETRICFROBENIUSNORM
