 
// THIS IS THE FULL FEATURE SET -- USE THIS AS TO DETERMINE SUBSETS 

 
  #define NNZ _NNZ 
  #define AVGNONZEROSPERROW _AVGNONZEROSPERROW 
  #define ABSOLUTENONZEROSUM _ABSOLUTENONZEROSUM 
  #define FROBENIUSNORM _FROBENIUSNORM 
  #define AVERAGEDIAGONALDISTANCE _AVERAGEDIAGONALDISTANCE            
  #define ROWVARIANCE _ROWVARIANCE 
  #define TRACE _TRACE 
  #define ABSOLUTETRACE _ABSOLUTETRACE 
  #define DIAGONALMEAN _DIAGONALMEAN 
  #define DIAGONALAVERAGE _DIAGONALAVERAGE    
  #define DIAGONALNONZEROS _DIAGONALNONZEROS   
  #define INFINITYNORM _INFINITYNORM 
  #define MAXNONZEROSPERROW _MAXNONZEROSPERROW 
  #define DIAGONALSIGN _DIAGONALSIGN 
  #define LOWERBANDWIDTH _LOWERBANDWIDTH 
  #define UPPERBANDWIDTH _UPPERBANDWIDTH 
  #define ROWDIAGONALDOMINANCE _ROWDIAGONALDOMINANCE 
  #define MINNONZEROSPERROW _MINNONZEROSPERROW 
  #define ONENORM _ONENORM 
  #define COLDIAGONALDOMINANCE _COLDIAGONALDOMINANCE 
  #define COLUMNVARIANCE _COLUMNVARIANCE 
  #define SYMMETRICITY _SYMMETRICITY 
  #define NONZEROPATTERNSYMMETRY _NONZEROPATTERNSYMMETRY 
  #define SYMMETRICINFINITYNORM _SYMMETRICINFINITYNORM 
  #define SYMMETRICFROBENIUSNORM _SYMMETRICFROBENIUSNORM 
  #define ANTISYMMETRICINFINITYNORM _ANTISYMMETRICINFINITYNORM 
  #define ANTISYMMETRICFROBENIUSNORM _ANTISYMMETRICFROBENIUSNORM


